### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by sigi2345** [ioBroker/ioBroker.vis-knob#5]
Kann man diese mal updaten?
Icon Sets sind in der RM Falsch!

**Comment by Apollon77** [comment]
RM? Was genau muss wie und wo geupdatet werden?

**Comment by sigi2345** [comment]
> RM? Was genau muss wie und wo geupdatet werden?

The preview does not match the content. The README shows wrong widgets.


Beispiele:
![Screenshot (2033)_LI](https://user-images.githubusercontent.com/41079106/76686418-7b7a8a80-661b-11ea-9099-4e982a8d5885.jpg)
